### ISSUE TITLE
high level function for harfbuzz package

### ISSUE THREAD

**Issue by eroux** [lualatex/luaotfload#314]
@michal-h21 asked for a few high level functions in [this comment on another issue](https://github.com/lualatex/luaotfload/issues/308#issuecomment-166306844), I'm opening a new issue for this. Don't hesitate to elaborate your request in the comment!

**Comment by michal-h21** [comment]
@eroux thanks. The `luatex-harfbuzz-shaper` process node lists before linebreak and uses Harfbuzz library to do text shaping, it means ligaturing, kerning, complex scripts handling etc. So it doesn't need to parse OpenType fonts for feature tags, it just needs to find a font file, parse it to get LuaTeX font object and set basic properties like various spaces, character dimensions etc.

What it currently does is that it [uses some code](https://github.com/michal-h21/luatex-harfbuzz-shaper/blob/master/hb_findfont.lua) originally from `luaotfload-tool` to parse font request (like `Linux Libertine O/I:+smcp`) for font features, load `luaotfload` font database and search it for the path to a font file.

The [fontloader](https://github.com/michal-h21/luatex-harfbuzz-shaper/blob/master/hb_fontload.lua), is modified version of an  [example from LuaTeX wiki](http://wiki.luatex.org/index.php/Use_a_TrueType_font), it only loads Harfbuzz font object and it also saves `map.backmap` from `fontloader` table. 

So my basic need is to have simple interface to query font DB,  parse font request (only actually requested features, not any default ones) and to apply some basic transformations to object returned by LuaTeX's `fontloader` library (set `parameters` table, handle unicode math tables, microtype handling, etc.). It would be also nice if it was possible to use caching mechanism, as loading some CJK fonts can take significant amount of time, but I understand that font format requested by `luaotfload` and `harfbuzz` are incompatible.

**Comment by eroux** [comment]
Do you think it would be reasonable to load `luaotfload` with a special config to query the font DB, or would it be better to have a new package `luatex-font-files-db`, that would be common between `luaotfload` and `luatex-harfbuzz-shaper`? About caching, if the format is not compatible then I suppose you have to handle this on the `luatex-harfbuzz-shaper` side... @phi-gamma what do you think?

**Comment by michal-h21** [comment]
As also other parts  of `luaotfload` than just font DB are used, special config would be best, I guess.

**Comment by phi-gamma** [comment]
···<date: 2015-12-22, Tuesday>···<from: Michal Hoftich>···

> @eroux thanks. The `luatex-harfbuzz-shaper` process node lists
> before linebreak and uses Harfbuzz library to do text shaping, it
> means ligaturing, kerning, complex scripts handling etc. So it
> doesn't need to parse OpenType fonts for feature tags, it just
> needs to find a font file, parse it to get LuaTeX font object and
> set basic properties like various spaces, character dimensions
> etc.

> What it currently does is that it [uses some code](https://github.com/michal-h21/luatex-harfbuzz-shaper/blob/master/hb_findfont.lua)
> originally from `luaotfload-tool` to parse font request (like
> `Linux Libertine O/I:+smcp`) for font features, load `luaotfload`
> font database and search it for the path to a font file.

> The > [fontloader](https://github.com/michal-h21/luatex-harfbuzz-shaper/blob/master/hb_fontload.lua),
> is modified version of an  [example from LuaTeX
> wiki](http://wiki.luatex.org/index.php/Use_a_TrueType_font), it
> only loads Harfbuzz font object and it also saves `map.backmap`
> from `fontloader` table. 

> So my basic need is to have simple interface to query font DB,
> parse font request (only actually requested features, not any
> default ones) and to apply some basic transformations to object
> returned by LuaTeX's `fontloader` library (set `parameters`
> table, handle unicode math tables, microtype handling, etc.). It
> would be also nice if it was possible to use caching mechanism,
> as loading some CJK fonts can take significant amount of time,
> but I understand that font format requested by `luaotfload` and
> `harfbuzz` are incompatible. 

1) You’re asking for much more than a “simple interface”. AFAICT
that harfbuzz library doesn’t do much apart from the shaping
part, thus covering only part of the functionality of the
fontloader. Since you’ve already chosen to depend on an external
library it seems rather obvious to offload the rest of the
infrastructure to the usual libraries -- Freetype, Fontconfig --
too, just like Xetex does.

2) Since HB does only the shaping part, your best chances of
getting it integrated with the fontloader are to first get it
working not with Luaotfload but with the Fontloader per se:
Target Context or, if you’re comfortable with staying a bit
behind, the generic loader. That’s where the development happens
and where the integration can be handled. On the Luaotfload end
this would quickly become an unsupportable mess.

3) Much of what you’re asking depends on infrastructure provided
by the fontloader. Other functionality like e. g. building the
names database will become much more intertwined with the
fontloader as the Fontforge library is gradually being phased
out. Implemented your way, you’d end up with the code of two
fontloader packages concurrently which is needless duplication.
Maybe after 1.0 the situation will improve. Right now it’s hard
enough to even support multiple concurrent versions of the
fontloader itself.

4) Unicode math, microtype, etc. are different packages. You’ll
have to contact the respective maintainers.

5) I have no idea in what way the font cache could be leveraged
for use with HB.

6) Please fix the license on your project.

**Comment by deepakjois** [comment]
It is not obvious to me why we need to offload ‘the rest of the infrastructure’ to libraries like Freetype, Fontconfig etc.

It would be great to not have to depend on Harfbuzz in the first place, but the reality is that ConTeXt’s fontloader does not support some scripts well. Indic support seems to be limited, and there are issues with Nastaliq fonts (see #292). Harfbuzz is a sophisticated shaping engine that is actively maintained, and supports these scripts well. We now have [luaharfbuzz] which provides Lua bindings to Harfbuzz as well.

[luaharfbuzz]:https://github.com/deepakjois/luaharfbuzz

Let’s consider the question, what does an alternative ‘infrastructure’ to shape text in LuaTeX will need:

a. font request syntax w/ support for specifying OpenType features to use
b. font database and querying
c. loading font data and metrics (for glyph and character data etc.).
d. … (maybe something I am missing)

My understanding is that (a) and (b) are provided in luaotfload. You mention that a lot of the functionality is intertwined with ConTeXt’s fontloader. It maybe something that is difficult to do, but it would be nice to consider the possibility of exposing that functionality to external libraries in some way.

As for (c), I was assuming that `fontloader` library from LuaTeX could be used. But from what you said in (3) above, the Fontforge library is being phased out. Does that mean `fontloader` package in LuaTeX will not exist as well? Where can we find out more about this? Were there some discussions on the LuaTeX mailing list?

So, it seems that a lot of the pieces that are needed exist in some form or the other. We don’t need libraries like FreeType and Fontconfig. In any case, I imagine writing Lua bindings for them would be much more complicated than writing luaharfbuzz was. At least for me, it won’t be worth the effort.

**Comment by michal-h21** [comment]
It seems that I will repeat some things which already said Deepak,
which summarized it really well. 

> 1) You’re asking for much more than a “simple interface”. AFAICT
> that harfbuzz library doesn’t do much apart from the shaping
> part, thus covering only part of the functionality of the
> fontloader. Since you’ve already chosen to depend on an external
> library it seems rather obvious to offload the rest of the
> infrastructure to the usual libraries -- Freetype, Fontconfig --
> too, just like Xetex does.

Yes, Harfbuzz is doing only shaping and everything it needs is unicode
text, font object and some properties like script, language, text
direction and OpenType features. We use Luaotfload for locating the
font, parsing script, language and features. Fontconfig would solve the
font locating problem, although it doesn't support fonts in TEXMF tree.
But we still have to parse `\font\name={Hello world:+smcp}` requests and
initialize the Lua font object. 

> 
> 2) Since HB does only the shaping part, your best chances of
> getting it integrated with the fontloader are to first get it
> working not with Luaotfload but with the Fontloader per se:
> Target Context or, if you’re comfortable with staying a bit
> behind, the generic loader. That’s where the development happens
> and where the integration can be handled. On the Luaotfload end
> this would quickly become an unsupportable mess.

I see, you are right. It is just that I am unfamiliar with Context.
By generic loader you mean table returned by Fontforge? 

> 
> 3) Much of what you’re asking depends on infrastructure provided
> by the fontloader. Other functionality like e. g. building the
> names database will become much more intertwined with the
> fontloader as the Fontforge library is gradually being phased
> out. Implemented your way, you’d end up with the code of two
> fontloader packages concurrently which is needless duplication.
> Maybe after 1.0 the situation will improve. Right now it’s hard
> enough to even support multiple concurrent versions of the
> fontloader itself.

OK, I was not aware of these changes. So instead of Fontforge, some new
library will be used, which will convert font directly to font object
needed by LuaTeX? 
> 
> 4) Unicode math, microtype, etc. are different packages. You’ll
> have to contact the respective maintainers.

In fact microtype works, to my surprise. I meant more setting correct
font parameters from Fontforge table, it seems that especially math
fonts needs some settings.  
> 
> 5) I have no idea in what way the font cache could be leveraged
> for use with HB.

It still needs a font object created from object created by Fontforge.
It takes quite some time to create it for large fonts, such as `Noto
Sans CJK KR`, I guess it is mainly because of calculating dimensions for
glyphs table. But it is nothing too much important.
> 
> 6) Please fix the license on your project.
> 

Thanks for reminding that, I am still forgetting abut this stuff :)

**Comment by u-fischer** [comment]
I'm closing the issue here, but added a reference at https://github.com/u-fischer/luaotfload/issues/85. @michal-h21 I'm not sure if it is still relevant in view of the development of harftex/luahbtex - if you could comment at the new issue it would be nice.
