### ISSUE TITLE
font name no longer enclosed in quotes (with \meaning)

### ISSUE THREAD

**Issue by schlcht** [lualatex/luaotfload#339]
Hi,

in previous versions, querying the meaning of a font-csname resulted in the font name being enclosed in quotes. With the current version from pretest, font names will only be enclosed in quotes if the name itself contains a space. Some code will make clearer what I mean: 

```
\input luaotfload.sty
\font\x="Vollkorn" 
\message{\expandafter\meaning\x}
\font\x="Charis SIL" 
\message{\expandafter\meaning\x}
\bye
```

Previously, this resulted in: 
```
select font "Vollkorn" 
select font "Charis SIL" 
```

while now it's:
```
select font Vollkorn 
select font "Charis SIL" 
```

Is this change intended? (It would make parsing much more difficult.)

**Comment by phi-gamma** [comment]
···<date: 2016-04-24, Sunday>···<from: schlcht>···

> Hi,
> 
> in previous versions, querying the meaning of a font-csname resulted in the font name being enclosed in quotes. With the current version from pretest, font names will only be enclosed in quotes if the name itself contains a space. Some code will make clearer what I mean: 
> 
> ```
> \input luaotfload.sty
> \font\x="Vollkorn" 
> \message{\expandafter\meaning\x}
> \font\x="Charis SIL" 
> \message{\expandafter\meaning\x}
> \bye
> ```
> 
> Previously, this resulted in: 
> ```
> select font "Vollkorn" 
> select font "Charis SIL" 
> ```
> 
> while now it's:
> ```
> select font Vollkorn 
> select font "Charis SIL" 
> ```
> 
> Is this change intended?

Yes: https://github.com/lualatex/luaotfload/issues/334

>                          (It would make parsing much more difficult.)

You can access components of the font name from Lua just fine.
Also we’re using Lua’s ``%q`` format specifier, so you can rely
on all contained quotes being escaped properly. If anything, that
guarantee should make parsing easier ;)

IIRC the quotes are there to begin with because Latex requires
that it be possible to feed ``\fontname \font`` back into
``\font`` for an identical definition. They’re not needed by the
fontloader itself. I’m open for suggestions on how to make your
life easier in this regard.

Best,
Philipp

**Comment by schlcht** [comment]
Yes, I was indeed concerned because I need to feed the font name back to \font, adding a feature to it. But as it turns out, good ol' \fontname is sufficient for my needs, so sorry for bothering.

**Comment by phi-gamma** [comment]
@schlcht I’m closing this since you seem content. If you need other means
to access the font name, don’t hesitate to reopen.

**Comment by schlcht** [comment]
No problem, thanks
