### ISSUE TITLE
fontloader of context from texlive 2016 can not be used -- missing font-ocl.lua

### ISSUE THREAD

**Issue by u-fischer** [lualatex/luaotfload#384]
When  I compile this minimal document in a current texlive 2016

```
\documentclass{article}
\usepackage{luaotfload}

\begin{document}
blub
\end{document}
```

and this entry in luaotfload.conf

```
 fontloader = context
```

I get an error due to a missing font-ocl.lua:

```
luaotfload | load : Loading module “font-ocl” from Context....016/texmf-dist
/tex/luatex/luaotfload/luaotfload-main.lua:198: module 'font-ocl.lua' not found:

```

(there is really no font-ocl.lua in the context folder in texlive, but it exists in the context minimals).

**Comment by phi-gamma** [comment]
···<date: 2016-10-12, Wednesday>···<from: u-fischer>···

> When  I compile this minimal document in a current texlive 2016
> 
> ```
> \documentclass{article}
> \usepackage{luaotfload}
> 
> \begin{document}
> blub
> \end{document}
> ```
> 
> and this entry in luaotfload.conf
> 
>      fontloader = context
> 
> I get an error due to a missing font-ocl.lua:
> 
> ```
> luaotfload | load : Loading module “font-ocl” from Context....016/texmf-dist
> /tex/luatex/luaotfload/luaotfload-main.lua:198: module 'font-ocl.lua' not found:
> 
> ```
> 
> (there is really no font-ocl.lua in the context folder in texlive, but it exists in the context minimals).

Yep, that’s the new color handling. The TL version probably won’t
work after the next release.

Best,
Philipp

**Comment by u-fischer** [comment]
Not quite sure what "*after* the next release" should mean as it doesn't work already.  

I understand that the table `context_modules` in `luaotfload-init.lua` is used for context in TL16 and the context minimals and so it bound to break with the older context if it wants to keep up with the minimals. Wouldn't it be better in the long run if this info would be in config files?

**Comment by phi-gamma** [comment]
2016-10-20 (Thursday), notifications@github.com (u-fischer):

> Not quite sure what "*after* the next release" should mean as
> it doesn't work already.  

Ah, I didn’t know that, sorry. The fontloader in Luaotfload is
indeed more recent than the one that TL Context has. They appear
to have simply diverged too much at the time I pulled the code.

> I understand that the table `context_modules` in
> `luaotfload-init.lua` is used for context in TL16 and the context
> minimals and so it bound to break with the older context if it
> wants to keep up with the minimals.

Correct.

>                                     Wouldn't it be better in the
> long run if this info would be in config files?

No since this way we can intervene. It has been necessary in the
past to add arbitrary code in between the loading steps. Although
this could be accomplished with an externally supplied list of
modules too by inserting hooks I don’t think it’s worth the
effort. Not to mention that this is not the only code that needs
to be kept in sync: font loading, features, etc. are tested only
against the loader we ship and are just as likely to not work as
the initialization.

Best,
Philipp
